/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Registro;
import Modelo.Tatuador;
import javax.swing.JOptionPane;
/**
 *
 * @author vina
 */
public class Jframe_AgregarTatuador extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_AgregarTatuador
     */
    public Jframe_AgregarTatuador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Jtxt_nombre_tatuador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jtxt_rut_tatuador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jtxt_ApellidoTatuador = new javax.swing.JTextField();
        Jtxt_correoTaTUADOR = new javax.swing.JTextField();
        Jtxt_fonoTatuador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jbtn_guardar_Tatuador = new javax.swing.JButton();
        Jchb_disponibilidad = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jtxt_nombre_tatuador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_nombre_tatuadorActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre");

        jLabel2.setText("Rut");

        jLabel3.setText("apellido");

        jLabel4.setText("correo");

        jLabel5.setText("fono");

        Jbtn_guardar_Tatuador.setText("guardar");
        Jbtn_guardar_Tatuador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardar_TatuadorActionPerformed(evt);
            }
        });

        Jchb_disponibilidad.setText("Disponibilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jtxt_nombre_tatuador, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(Jtxt_rut_tatuador)
                    .addComponent(Jtxt_ApellidoTatuador)
                    .addComponent(Jtxt_correoTaTUADOR)
                    .addComponent(Jtxt_fonoTatuador)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jchb_disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Jbtn_guardar_Tatuador)))))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jtxt_nombre_tatuador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jtxt_rut_tatuador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jtxt_ApellidoTatuador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addComponent(Jtxt_correoTaTUADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addComponent(Jtxt_fonoTatuador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addComponent(Jchb_disponibilidad)
                .addGap(18, 18, 18)
                .addComponent(Jbtn_guardar_Tatuador)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtxt_nombre_tatuadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_nombre_tatuadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxt_nombre_tatuadorActionPerformed

    private void Jbtn_guardar_TatuadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardar_TatuadorActionPerformed
    String rut_tatuador, nom_tatuador, ap_tatuador,correo_tatuador;
    int fono_tatuador;
    boolean disponibilidad;
    nom_tatuador = this.Jtxt_nombre_tatuador.getText();
    ap_tatuador = this.Jtxt_ApellidoTatuador.getText();
    rut_tatuador = this.Jtxt_rut_tatuador.getText();
    correo_tatuador = this.Jtxt_correoTaTUADOR.getText();
    fono_tatuador =Integer.parseInt(this.Jtxt_fonoTatuador.getText());
    disponibilidad = this.Jchb_disponibilidad.isSelected(); //0-1
    Tatuador tatuador = new Tatuador(0, rut_tatuador, nom_tatuador, ap_tatuador, correo_tatuador, fono_tatuador, disponibilidad);
    Registro reg = new Registro();
    
    reg.AgregarTatuador(tatuador);
    
        JOptionPane.showConfirmDialog(null, "tatuador ya registrado","ingreso",1);
    }//GEN-LAST:event_Jbtn_guardar_TatuadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_AgregarTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_AgregarTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_AgregarTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_AgregarTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_AgregarTatuador().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_guardar_Tatuador;
    private javax.swing.JCheckBox Jchb_disponibilidad;
    private javax.swing.JTextField Jtxt_ApellidoTatuador;
    private javax.swing.JTextField Jtxt_correoTaTUADOR;
    private javax.swing.JTextField Jtxt_fonoTatuador;
    private javax.swing.JTextField Jtxt_nombre_tatuador;
    private javax.swing.JTextField Jtxt_rut_tatuador;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
