/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Registro;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.ParseException;
import Modelo.Tatuador;
import java.util.ArrayList;
/**
 *
 * @author josen
 */
public class Jframe_ModificarDtos1 extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_ModificarDtos
     */
    Registro reg = new Registro();
    private String disponibilidad;
    
    public Jframe_ModificarDtos1() {
        initComponents();
        setSize(600, 400);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtxtcorreo = new javax.swing.JTextField();
        jtxtnombre = new javax.swing.JTextField();
        jtxtapellido = new javax.swing.JTextField();
        jtxtfono = new javax.swing.JTextField();
        JtxtIdabuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JtxtBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jch_Disponibilidad = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        Jbtn_Regresar_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 218, -1, -1));
        getContentPane().add(jtxtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, -1));

        jtxtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, -1));
        getContentPane().add(jtxtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, -1));
        getContentPane().add(jtxtfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, -1));
        getContentPane().add(JtxtIdabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, -1));

        jLabel1.setText("Rut a buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, -1));

        JtxtBuscar.setText("buscar");
        JtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(JtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 106, -1));

        jLabel2.setText("nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setText("apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 55, 30));

        jLabel4.setText("fono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 55, 30));

        jLabel5.setText("correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 37, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 0, 5, 0));

        jch_Disponibilidad.setText("disponibilidad");
        getContentPane().add(jch_Disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 221, 85, -1));

        jPanel1.setBackground(new java.awt.Color(92, 94, 117));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.setToolTipText("");

        Jbtn_Regresar_menu.setBackground(new java.awt.Color(127, 127, 159));
        Jbtn_Regresar_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jbtn_Regresar_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon_Return.png"))); // NOI18N
        Jbtn_Regresar_menu.setText("Regresar");
        Jbtn_Regresar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Regresar_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Jbtn_Regresar_menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Jbtn_Regresar_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreActionPerformed

    private void JtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtBuscarActionPerformed
        // TODO add your handling code here:
        
        
        String rut_tatuador = this.JtxtIdabuscar.getText();
        
        
        Tatuador tatuador1 = new Tatuador();

        tatuador1 = reg.buscarTatuador(rut_tatuador);
        this.jtxtnombre.setText(tatuador1.getNom_tatuador());
        this.jtxtapellido.setText(tatuador1.getAp_tatuador());
        this.jtxtcorreo.setText(tatuador1.getCorreo_tatuador());
        this.jtxtfono.setText(String.valueOf(tatuador1.getFono_tatuador()));
        
        
        

    }//GEN-LAST:event_JtxtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fono;
        String num_tatuador;
        boolean disponibilidad;
        String rut_tatuador, nombre, apellido, correo;
        num_tatuador = this.jTextField1.getText();
        
        rut_tatuador = this.JtxtIdabuscar.getText();
        nombre = this.jtxtnombre.getText();
        apellido = this.jtxtapellido.getText();
        correo = this.jtxtcorreo.getText();
        fono = Integer.parseInt(this.jtxtfono.getText());
        disponibilidad = this.jch_Disponibilidad.isSelected();
        
        reg.ActualizarTatto(nombre, apellido, correo, fono, disponibilidad);
        
        JOptionPane.showMessageDialog(null, "Datos del tatuador actualizador correctamente", "Actualizar", 2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jbtn_Regresar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Regresar_menuActionPerformed
        // TODO add your handling code here:
        this.hide();
        Jframe_ModificarDtos1 reserva = new Jframe_ModificarDtos1();
        reserva.setVisible(false);
    }//GEN-LAST:event_Jbtn_Regresar_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_ModificarDtos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_ModificarDtos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_ModificarDtos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_ModificarDtos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_ModificarDtos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Regresar_menu;
    private javax.swing.JButton JtxtBuscar;
    private javax.swing.JTextField JtxtIdabuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jch_Disponibilidad;
    private javax.swing.JTextField jtxtapellido;
    private javax.swing.JTextField jtxtcorreo;
    private javax.swing.JTextField jtxtfono;
    private javax.swing.JTextField jtxtnombre;
    // End of variables declaration//GEN-END:variables
}
